version: '3.8'

services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./app:/app
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"